# Site settings
title: Sommaire Entier
email: w407022008@gmail.com
description: Community Site
baseurl:
url:
twitter_username:
github_username:  w407022008

# Build settings
markdown: kramdown
permalink: pretty
